services:
  - type: web
    name: estatelink
    runtime: python310
    plan: free
    buildCommand: "bash build.sh"
    startCommand: "gunicorn config.wsgi:application"
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.14
      - key: DEBUG
        value: "False"
      - key: SECRET_KEY
        value: 'django-insecure-9x#@$%^&*()_+-=[]{}|;:,.<>?/~`felixestatelink2026'
      - key: ALLOWED_HOSTS
        value: "estatelink-app.onrender.com,localhost,127.0.0.1"
      - key: CSRF_TRUSTED_ORIGINS
        value: "https://estatelink-app.onrender.com,http://localhost,http://127.0.0.1"

databases:
  - name: postgres
    ipAllowList: []
