# Generated by Django 6.0.5 on 2026-05-25 04:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='waterorder',
            name='vendor_response',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='watervendor',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='watervendor', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='customtab',
            name='icon_svg',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='customtab',
            name='url',
            field=models.CharField(max_length=200),
        ),
    ]
