# Generated by Django 6.0.5 on 2026-05-25 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_waterorder_vendor_response_watervendor_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='waterorder',
            name='litres',
            field=models.IntegerField(blank=True, help_text='Litres of water needed', null=True),
        ),
        migrations.AddField(
            model_name='waterorder',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Price willing to pay (KSh)', max_digits=10, null=True),
        ),
    ]
